### ISSUE TITLE
PLCTool funciona en una VM?

### ISSUE THREAD

**Issue by k4n4n** [TarlogicSecurity/PLCTool#3]
Hola!

He compilado todo tal y como se comenta en las instrucciones (tanto Candleblow en la placa base) y compilado PLCTool en una máquina virtual, pero me queda la inquietud de saber si funciona correctamente en un entorno virtual o mejor en un host fisico?

gracias!

slds,

**Comment by antoniovazquezblanco** [comment]
PLCTool ha sido parcialmente desarrollado en máquinas virtuales y ha sido probado en las mismas. La herramienta debería funcionar bien independientemente de que se encuentre en un entorno virtual o host físico.

Un saludo
