### ISSUE TITLE
PLCTool en Windows?

### ISSUE THREAD

**Issue by k4n4n** [TarlogicSecurity/PLCTool#4]
Buenas!

Por otra parte me gustaría saber si es posible compilar y ejecutar PLCTool en un sistema operativo basado en Windows?

gracias,

slds,

**Comment by antoniovazquezblanco** [comment]
PLCTool no ha sido probado en Windows. El código fuente actual no compila en Windows.

Sería posible portar el código a Windows. Una de las partes del código a modificar sería el soporte para interactuar con puertos serie, que podría ser integrado mediante https://github.com/sigrokproject/libserialport u otros.

En resumen, actualmente no es posible. Requeriría trabajo de programación.

Gracias
